§version: "3.0"

services:

  postgres:
    container_name: replaceme-postgres
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password2
      POSTGRES_USER: postgres
      POSTGRES_DB: replaceme
    ports:
      - "5432:5432"