spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
  mvc:
    servlet:
      path: /api

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      show-components: always