spring:
  profiles:
    active: dev
  datasource:
    url: ${replaceme-database-url}
    username: ${replaceme-database-user}
    password: ${replaceme-database-password}
  flyway:
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    servlet:
      path: /api/v1

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      show-components: always